# Generated by Django 5.1.2 on 2024-10-31 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_profit', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('img_filename', models.CharField(blank=True, max_length=300, null=True)),
                ('pair', models.CharField(max_length=15)),
                ('order_type', models.CharField(max_length=15)),
                ('lots', models.FloatField()),
                ('open_datetime', models.DateTimeField()),
                ('close_datetime', models.DateTimeField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField()),
                ('commission', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
