# Generated by Django 5.1.2 on 2024-11-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='img_filename',
            field=models.ImageField(blank=True, null=True, upload_to='journals_images/'),
        ),
    ]
