# Generated by Django 5.1.2 on 2024-11-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_img_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='img_filename',
            field=models.ImageField(upload_to='journals_images/'),
        ),
    ]
