# Generated by Django 5.1.2 on 2024-11-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journal_img_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='operation_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='journal',
            name='img_filename',
            field=models.ImageField(upload_to='trading_intelligence/files/journal_imgs'),
        ),
    ]
